name: Build cache
description: Saves or restores the build cache keyed by SHA

inputs:
  mode:
    description: 'save or restore'
    required: true
  cache-name:
    description: Cache name prefix
    required: false
    default: cache-builds
  path:
    description: Cache path(s)
    required: false
    default: build

runs:
  using: composite
  steps:
    - name: Restore build cache
      if: inputs.mode == 'restore'
      uses: actions/cache/restore@caa296126883cff596d87d8935842f9db880ef25 # v5
      with:
        path: ${{ inputs.path }}
        key: ${{ inputs.cache-name }}-${{ github.sha }}

    - name: Save build cache
      if: inputs.mode == 'save'
      uses: actions/cache/save@caa296126883cff596d87d8935842f9db880ef25 # v5
      with:
        path: ${{ inputs.path }}
        key: ${{ inputs.cache-name }}-${{ github.sha }}
