name: Docker build and push
description: Prepares, tags, and builds and pushes Docker images

inputs:
  images:
    description: Docker image name(s) to use as base for tags
    required: true
  tags:
    description: Docker tag rules (docker/metadata-action syntax)
    required: false
    default: |
      type=schedule
      type=ref,event=branch
      type=ref,event=tag
      type=ref,event=pr
  context:
    description: Build context
    required: false
    default: '.'
  platforms:
    description: Target platforms
    required: false
    default: 'linux/amd64'
  pull:
    description: Always pull base images
    required: false
    default: 'true'
  push:
    description: Push result to the registry
    required: false
    default: 'true'
  prepare-script:
    description: Script to run before building (e.g. ./prep_docker.sh)
    required: false
    default: ''

outputs:
  tags:
    description: Generated Docker tags
    value: ${{ steps.meta.outputs.tags }}
  labels:
    description: Generated Docker labels
    value: ${{ steps.meta.outputs.labels }}

runs:
  using: composite
  steps:
    - name: Prepare Docker context
      if: ${{ inputs.prepare-script != '' }}
      shell: bash
      run: ${{ inputs.prepare-script }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
      with:
        images: ${{ inputs.images }}
        tags: ${{ inputs.tags }}

    - name: Build and push
      uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
      with:
        context: ${{ inputs.context }}
        pull: ${{ inputs.pull }}
        push: ${{ inputs.push }}
        platforms: ${{ inputs.platforms }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
