name: Setup JDK and Gradle
description: Sets up GraalVM JDK and Gradle

inputs:
  java-version:
    description: Java version to use
    required: false
    default: '25'
  java-distribution:
    description: Java distribution to use
    required: false
    default: 'graalvm'

runs:
  using: composite
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5
