name: Upload release asset
description: Uploads files, or files matching a glob, to a GitHub release

inputs:
  tag:
    description: Release tag name
    required: true
  file:
    description: Path or glob of the file(s) to upload
    required: true
  repo:
    description: GitHub repository (owner/repo)
    required: false
    default: ${{ github.repository }}
  token:
    description: GitHub token for authentication
    required: true


runs:
  using: composite
  steps:
    - name: Setup release name
      id: setup
      shell: bash
      env:
        TAG: ${{ inputs.tag }}
      run: |
          if [ -n "${TAG}" ]; then
            channel="release"
            version="${TAG#v}"
            echo "create_release=false" >> $GITHUB_OUTPUT
            echo "release_name=$channel-$version" >> $GITHUB_OUTPUT
            echo "release_channel=$channel" >> $GITHUB_OUTPUT
            echo "release_version=$version" >> $GITHUB_OUTPUT
          else
            channel="nightly"
            version="$(date -u +%Y%m%d)"
            echo "create_release=true" >> $GITHUB_OUTPUT
            echo "release_name=$channel-$version" >> $GITHUB_OUTPUT
            echo "release_channel=$channel" >> $GITHUB_OUTPUT
            echo "release_version=$version" >> $GITHUB_OUTPUT
          fi

    - name: Update Nightly tag
      if: ${{ steps.setup.outputs.create_release == 'true' && steps.setup.outputs.release_channel == 'nightly' }}
      shell: bash
      run: |
          git tag -f nightly
          git push origin -f nightly

    - name: Update Nightly release
      if: ${{ steps.setup.outputs.create_release == 'true' && steps.setup.outputs.release_channel == 'nightly' }}
      uses: 'ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd'
      env:
        GH_TOKEN: ${{ inputs.token }}
        INPUT_TAG: ${{ inputs.tag }}
        INPUT_FILE: ${{ inputs.file }}
        INPUT_REPO: ${{ inputs.repo }}
      with:
          prerelease: true
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          generateReleaseNotes: true
          name: ${{ steps.setup.outputs.release_name }} # nightly-YYYYMMDD
          tag: nightly
          artifacts: ${INPUT_FILE}
          repo: "${ INPUT_REPO }"

    - name: "Release ${{ steps.setup.outputs.release_version }}"
      if: ${{ steps.setup.outputs.create_release == 'true' && steps.setup.outputs.release_channel == 'release' }}
      uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd
      env:
        GH_TOKEN: ${{ inputs.token }}
        INPUT_TAG: ${{ inputs.tag }}
        INPUT_FILE: ${{ inputs.file }}
        INPUT_REPO: ${{ inputs.repo }}
      with:
        draft: true
        prerelease: false
        makeLatest: true
        name: Release - ${{ steps.setup.outputs.release_version }}
        tag: ${{ steps.setup.outputs.release_name }}
        artifacts: ${INPUT_FILE}
        repo: "${ INPUT_REPO }"
